# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

---
name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

env:
  GO_VERSION: "1.19"

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Check REUSE compliance
        uses: fsfe/reuse-action@v2
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build executable
        run: go build
      - name: Run tests
        run: go test -cover -count=1 ./...
